### ISSUE TITLE
Missing dependencies in README

### ISSUE THREAD

**Issue by ricovangenugten** [Xerbo/LeanHRPT-Demod#1]
This is not really a bug, but the following dependencies are missing from the README file:

- libsndfile1-dev
- libsoapysdr-dev

Including them might help somebody in compiling from source without having to search the web first. :)

**Comment by Xerbo** [comment]
I'm also wondering whether I should include build (and install) instructions for libcorrect, as it probably isn't obvious at first a lot of people.

**Comment by ricovangenugten** [comment]
Oh, for me that went without any trouble following the build instructions in their README.
