### ISSUE TITLE
Can't open a WAV file

### ISSUE THREAD

**Issue by robertogonzalezp** [Xerbo/LeanHRPT-Demod#11]
Hello!

I wanna run LearnHRPT-Demod with a .wav file from a NOAA18 (HRPT) but when I push the start bottom, LearnHRPT-Demod closes and don't produce any output file (.bin).

Can you help me please? I am using the lastest version in Windows.  I can provide you with the .wav file that I use if necessary, but it's heavy, around 5 GB.

Thank you so much.

**Comment by Xerbo** [comment]
My best guess is that the WAV is from some software that doesn't write RF64, and thus all [files over 4 GiB](https://en.wikipedia.org/wiki/WAV#Limitation) are corrupted. In order to read these you should use the "raw" source.

**Comment by robertogonzalezp** [comment]
Okey, thank you for the help. 

I can't use the "raw" because the .wav file that I used is from Reddit. I'm doing tests for my final project at the university before setting up my own antenna and getting my own data, so I can't use a "raw" to test the program.

Would you be so kind to provide me a raw file so I can test the program?

Thank you so much!

**Comment by Xerbo** [comment]
A WAV file is basically just raw data with a header, you can find the sample rate under file properties and the format is most likely `short`.

**Comment by robertogonzalezp** [comment]
That's true, now it works. Thank you for the help and sorry for the inconvenience.
