### ISSUE TITLE
LeanHRPT-Demod is missing .dlls

### ISSUE THREAD

**Issue by arelli** [Xerbo/LeanHRPT-Demod#17]
**Describe the bug**
Hi,
When I try to run the executable from the last release(v0.1.3) on a fresh Windows 10 installation, and I get some error messages that says a .dll is missing, several times. The mentioned .dlls are: MSVCP140.dll, VCOMP140.dll, VCRUNTIME140.dll, VC_RUNTIME140_1.dll.  I also tried it with the v0.1.2 release, it is the same.
![image](https://github.com/Xerbo/LeanHRPT-Demod/assets/19637856/3954aa6c-398b-404a-aedc-e3eab2ef718a)

**To Reproduce**
Download the .zip file from releases, unzip it, and run the "LeanHRPT-Demod" executable file.

**Expected behavior**
I expected the .exe file to open the Demod window when double clicked.

**Platform**
 - Windows 10 Pro, build 19045

**Version**
v0.1.3, v0.1.2

**Comment by sgcderek** [comment]
Considering that it's a new OS installation it seems like you're just missing Visual Studio Runtime.
https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist
