### ISSUE TITLE
Bias tee not working on RTL-SDR V3

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Demod#2]
**Describe the bug**
Bias tee does not turn on on Windows 10, RTL-SDR V3

**To Reproduce**
Open LeanHRPT-Demod, plug in an RTL-SDR, attempt to turn on the bias tee. 

**Expected behavior**
Bias tee will turn on. 

**Platform**
 - Windows

**Version**
All versions have this bug. I got the latest (Fix Pluto(?) and better Bias Tee support
Build #77: Commit 9fd4093 pushed by Xerbo) and it still has it.

**Comment by Xerbo** [comment]
The version of SoapySDR that comes bundled with LeanHRPT (2020.01.26) doesn't contain a Bias Tee enabled librtlsdr, however more modern versions do. I'll look into bundling a more modern version.

I've tried running it with a more up to date version of SoapySDR which does have bias tee support but it segfaults shortly after clicking start.

**Comment by IZ5RZR** [comment]
Partially solved with this trick I suppose
Download this driver and unzip on some folder than start bias tee on.bat, open leanhrpt demod and start to play
[Bias tee ok.zip](https://github.com/Xerbo/LeanHRPT-Demod/files/7799465/Bias.tee.ok.zip)

**Comment by zeke800** [comment]
Thank you so much!! It didn't work for me, but I'll try rtl-eeprom and see. The amplifier lightbulb would light up when I ran the BAT, but then when I started live mode it would turn off. Happy New Year!

**Comment by Xerbo** [comment]
a20ca21 contains a much newer of SoapySDR, which should fix the issue.

**Comment by zeke800** [comment]
Everything works perfectly!! Thank you so much! One final question - why does Norton Antivirus perk up with 'trying to access internet' warnings? 
![Screenshot 2022-01-03 113105](https://user-images.githubusercontent.com/82127189/147955295-12bda8c9-b555-4b42-8e30-01726ab63299.png)

**Comment by Xerbo** [comment]
Thats most likely from [SoapyRemote](https://github.com/pothosware/SoapyRemote) scanning for networked SDR devices

**Comment by zeke800** [comment]
Oh - thank you so much! Another issue I noticed with the new version - LeanHRPT Demod can't open wav files anymore - it crashes.
