### ISSUE TITLE
The Bias tee does not work

### ISSUE THREAD

**Issue by IZ5RZR** [Xerbo/LeanHRPT-Demod#4]
**Describe the bug**
When I use LeanHRPT demod in both win 10 and 11 windows, the bias tee does not activate. That is, the Bias tee flag cannot be activated, it remains unselectable.
I have tried both with original RTL V.3, both with sdrplay rsp2pro and original hackrf one.
The only way to activate the bias tee and only on RTL V3 is to first run the command from cmd bias tee on (the driver found on the network).
Is there a way to solve the problem? Otherwise, no sdr can be used.
With similar tests done with satdump, however, the bias tee works.
Thank you
IZ5RZR - Max
**Platform**
 - Windows 10 and 11

**Version**
Latest version

**Comment by Xerbo** [comment]
Try [this build](https://github.com/Xerbo/LeanHRPT-Demod/actions/runs/1650501316)

**Comment by Xerbo** [comment]
Marked as wontfix until I have further information
