### ISSUE TITLE
SatDump does not recognize the format/outputs garbage

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Demod#5]
**Describe the bug**
When you set the file to process in satdump, it completely is unable to decode it and outputs some weird lines. When I run the file through LeanHRPT Decode it processes perfectly with almost 4000 clear lines. Why is this happening? 

**To Reproduce**
Go to satdump, then run any HRPT file from NOAA or Meteor. 

**Expected behavior**
Decode correctly.

**Platform**
 - Windows

**Version**
Latest

Satdump output:
![MSU-MR-4-EQU](https://user-images.githubusercontent.com/82127189/151864508-92bedc16-a208-412b-ae58-0ba7fb8718e3.png)

LeanHRPT output:
![meteorjan23 (reduced resolution)](https://user-images.githubusercontent.com/82127189/151864585-6c8b45b5-d88e-4183-9302-92555db11186.png)

Thanks!

**Comment by Xerbo** [comment]
LeanHRPT-Demod outputs raw data. SatDump doesn't support that, for some reason it opts to use soft symbols.

**Comment by zeke800** [comment]
Thank you for your reply! :) 

I really want to process files through satdump though... is there absolutely any way to do this? 

Thanks!

**Comment by zeke800** [comment]
Also for some reason it only outputs something on "cadu" level. On soft it just outputs corrupted images.

**Comment by Xerbo** [comment]
Frankly this is a SatDump issue, there is no purpose in using soft symbols for NOAA/Meteor, since it gets sliced into binary one step later anyway (what LeanHRPT-Demod outputs).

**Comment by Xerbo** [comment]
ref [LeanHRPT-Decode#16](https://github.com/Xerbo/LeanHRPT-Decode/issues/16)

**Comment by zeke800** [comment]
For anyone looking, use `bin2cadu.exe in.bin out.cadu` for Meteor
and `bin2raw16.exe in.bin out.raw16` for NOAA. The executables are available from LeanHRPT-Decode.
