### ISSUE TITLE
GAC?

### ISSUE THREAD

**Issue by zeke800** [Xerbo/LeanHRPT-Demod#6]
**Describe the feature you would like**
Is it possible to demodulate and decode GAC? Is it LHCP or RHCP, too?

Thanks!

**Comment by Xerbo** [comment]
NOAA-19 is LHCP, NOAA-18/15 are *probably* RHCP though. You can find out when the dumps begin with [this](https://github.com/sgcderek/polrschd)

**Comment by Xerbo** [comment]
Just going to use this issue to ping you, but I made some improvements to the GAC demodulator since 8e38df2, so might be worth checking out.
